version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Alaska@63
    volumes:
      - /pgdata/test:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    image: todo-backend:latest
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    restart: unless-stopped