spring:
  datasource:
    url: jdbc:postgresql://dpg-cqtouktds78s739r3260-a.singapore-postgres.render.com/todo_ktf2

    username: vahathi
    password: HMNVlyW4MBWACDzxk4xjgotHjdIVvZ1G
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      sql:
        init: always
        test:
          openapi:
            dev-url: https://todo-backend-3edz.onrender.com
            test:
              openapi:
                dev-url: https://todo-backend-3edz.onrender.com
                prod-url: http://phoenixapi.ddns.net:9000/
            springdoc:
              packages-to-scan: com.vahathi.test.controller
              swagger-ui:
                filter: true
                operationsSorter: method
                tagsSorter: alpha
                tryItOutEnabled: true
                logging:
                  level:
                    org:
                      hibernate:
                        type: trace
server:
  port: 80
